notifications:
  slack: 9livesdatazpp:rEIvPs5yjBw9GEjggS388fDO#travis

language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3

matrix:
  include:
    - python: 2.7
      env: JYTHON=true
    - python: 2.7
      env: SCA=true
    - python: 3.5
      env: SCA=true
    - python: 3.5
      os: osx
      language: generic

cache:
  - pip
  - directories:
    - $HOME/jython-pip
    - $HOME/jython
    - $HOME/.virtualenv/jython
    - $HOME/.virtualenv/python3-osx

before_install:
  - uname -a
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then lsb_release -a; fi
  # get jython
  - if [ -n "$JYTHON" -a ! -f "$HOME/.virtualenv/jython/bin/activate" ]; then wget http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.1b3/jython-installer-2.7.1b3.jar -O jython-installer-2.7.1b3.jar; else echo skip; fi
  - if [ -n "$JYTHON" -a ! -f "$HOME/.virtualenv/jython/bin/activate" ]; then java -jar jython-installer-2.7.1b3.jar --silent --directory "$HOME/jython"; else echo skip; fi
  # install a custom version of pip, as standard pip doesn't work on jython (https://github.com/jythontools/pip/commits/develop)
  - if [ -n "$JYTHON" -a ! -d "$HOME/jython-pip" ]; then mkdir ~/jython-pip; else echo skip; fi
  - if [ -n "$JYTHON" -a ! -f ~/jython-pip/pip-7.1.2-py2.py3-none-any.whl ]; then wget https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.2-py2.py3-none-any.whl -O ~/jython-pip/pip-7.1.2-py2.py3-none-any.whl; else echo skip; fi
  # create jython virtualenv
  - if [ -n "$JYTHON" -a ! -f "$HOME/.virtualenv/jython/bin/activate" ]; then virtualenv --system-site-packages --extra-search-dir="$HOME/jython-pip" -p "$HOME/jython/bin/jython" "$HOME/.virtualenv/jython"; else echo skip; fi
  - if [ -n "$JYTHON" ]; then source "$HOME/.virtualenv/jython/bin/activate"; fi
  # install python3 on OS X
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv -p python3 "$HOME/.virtualenv/python3-osx"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source "$HOME/.virtualenv/python3-osx/bin/activate"; fi
  - virtualenv --version

install:
  # install PyYAML on Jython manually before pip tries to do it and fails
  - if [ -n "$JYTHON" -a ! -f "$HOME/.virtualenv/jython/Lib/site-packages/PyYAML-3.11-py2.7.egg-info" ]; then wget https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.tar.gz; tar -zxf PyYAML-3.11.tar.gz; cd PyYAML-3.11/; wget http://pyyaml.org/raw-attachment/ticket/163/jython-setup.patch; patch < jython-setup.patch; python setup.py install; cd -; fi
  # `pip install -r requirements.txt` does not work on jython 2.7.1b2
  # installing regex on jython fails (jython can't compile the native extension), this awk filter prevents it
  - cat requirements*.txt | awk \"${JYTHON:-False}'" == "True" && /^regex/ || ! /^regex/' | xargs pip install
  - if [ -z "$SCA" ]; then python setup.py develop; else echo skip; fi

before_script:
  # Before runing the test case, we need to make jython run some code as in first run it can put something on stdout
  - if [ -n "$JYTHON" ]; then python -c "print ''"; else echo skip; fi

script:
  - if [ -n "$SCA" -a -n "$TRAVIS_COMMIT_RANGE" ]; then git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep '\.py$' | xargs yapf --diff setup.py || exit; else echo skip; fi
  - if [ -n "$SCA" -a -z "$TRAVIS_COMMIT_RANGE" ]; then yapf --diff --recursive . || exit; else echo skip; fi
  - if [ -n "$SCA" ]; then pyflakes . || exit; else echo skip; fi
  - if [ -n "$SCA" ]; then isort --order-by-type --recursive --line-width 100 --diff --verbose --check-only || exit; else echo skip; fi
  - if [ -n "$SCA" ]; then grep -r '\_\_metaclass\_\_' whylog/ && exit 1 || true; else echo skip; fi
  - if [ -n "$SCA" ]; then exit; else echo skip; fi
  - python setup.py nosetests
