notifications:
  slack:
    secure: O0jV38fRjAKInDl28LiHPGjOjp0uRMM6SvJSCCHsx5dvxynZSFwfLkrdKxFTomMb61gBRIgnrjbTzHMkttVd2O0GdNNWgo5NbAfm731lua360qtq7toW4hJtnHauFhrWiXLL1TNpliqT+OEzlfO/VCx6I3VMunKBBwPRkCRQ3EhlxF7Ga7YJ0JptN60PkIqlmys34yyqcZx7Ui+tflfQ5GoLm58kabe9trdYaRcxFo9rCe8pO2A6MEDNrUHlxIJewC4JuWOdDfKS60iTGUI2+KZePuCUfQiRT0HkJrqhisnM+0WR5G/1eb4QOs1sQRsUNsVJHbfWead+keknx/4smkSHQkv9n/SX9TboPscS2syGgA8TWQoHn7EBaJWs7Yg+GlXZDjjqAqVCM4r7kwwHVpoq5HJ2Dw1YqFARobtLLDsMcftzngaWw6dwD+HxMYzM3ebCX1bx62dncvTF5nqEqDp2ivemyfjfhAGb2rX9H0g0LiYB2P+choqkkaqN1ybrhR/l8AM4pheV7QzzpcDCz7idnx176mitgWMlqiPBJa9wDx0kScBGCeU/Wg9xFoAu7Ek3pH+Xy+RAI2REXCCqTYSJjUmGsvWrauaf+dyYRjOMfJeECNzQqhudkndxGsSZXTjxzX2ZV/R0STmZP8r1rT97MPg+3ZCM7jnZDjSlBPo=

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"

matrix:
  include:
    - python: "2.7"
      env: JYTHON=true
    - python: "2.7"
      env: YAPF=true
    - python: "3.5"
      env: YAPF=true

before_install:
  - uname -a
  - lsb_release -a
  - virtualenv --version
  # get jython
  - if [ -n "$JYTHON" ]; then wget http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.1b2/jython-installer-2.7.1b2.jar -O jython-installer-2.7.1b2.jar; fi
  - if [ -n "$JYTHON" ]; then java -jar jython-installer-2.7.1b2.jar --silent --directory $HOME/jython; fi
  # install a custom version of pip, as standard pip doesn't work on jython (https://github.com/jythontools/pip/commits/develop)
  - if [ -n "$JYTHON" ]; then mkdir ~/jython-pip; fi
  - if [ -n "$JYTHON" ]; then wget https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.2-py2.py3-none-any.whl -O ~/jython-pip/pip-7.1.2-py2.py3-none-any.whl; fi
  # create jython virtualenv
  - if [ -n "$JYTHON" ]; then virtualenv --system-site-packages --extra-search-dir=$HOME/jython-pip -p $HOME/jython/bin/jython $HOME/.virtualenv/jython; fi
  - if [ -n "$JYTHON" ]; then source $HOME/.virtualenv/jython/bin/activate; fi

install:
  # `pip install -r requirements.txt` does not work on jython
  - cat requirements*.txt | xargs pip install
  - if [ -z "$YAPF" ]; then python setup.py develop; fi

before_script:
  # Before runing the test case, we need to make jython run some code as in first run it can put something on stdout
  - if [ -n "$JYTHON" ]; then python -c "print ''"; fi

script:
  - if [ -n "$YAPF" ]; then yapf --diff --recursive .; exit; fi
  - python setup.py nosetests
